### ISSUE TITLE
Bug: inboxsdk.com/build/platform-implementation.js returns 404

### ISSUE THREAD

**Issue by emildayan** [InboxSDK/InboxSDK#1227] opened 2024-11-01 11:43 UTC
All extensions using InboxSDK is broken as of this morning.

https://www.inboxsdk.com/build/platform-implementation.js
Returns 404 not found

Access to XMLHttpRequest at 'https://www.inboxsdk.com/build/platform-implementation.js' from origin 'https://mail.google.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by matijasss** [comment] 2024-11-01 13:03
I confirm the issue is present and all our extensions are blocked

**Comment by aleemstreak** [comment] 2024-11-01 14:59
The SDK no longer supports remote loading as it is no longer supported by chrome, edge and safari. Please upgrade to the MV3 inboxsdk library.

**Comment by shashikiran-im** [comment] 2024-11-01 15:50
Dear Aleemstream / InboxSDK Team,

Our extension customers are impacted due to 404 error while loading inboxSDK JS from the path https://www.inboxsdk.com/build/platform-implementation.js (404 error).
			
I kindly request you to make platform-implementation.js available for a little longer time so that our customers can continue using it (as we are already in the process of migrating our extension from MV2 to MV3). 
It would be greatly appreciated if you could continue support MV2 for now and announce timeline on when you stop supporting it so that we will make transmit to MV3 in the meantime.

Thanks in Advance,
Shashikiran

**Comment by davemarkle** [comment] 2024-11-01 19:19
I am using the mv3 library exactly like the hello world example and receiving the same JS CORS error and a 404 fail on that same file. There is something inside the inboxsdk JS that is still making calls to a inboxsdk.com. I’m on npm version 2.1.64.

**Comment by aleemstreak** [comment] 2024-11-01 19:42
That should not be the case, can you post code for how you are loading the SDK?

**Comment by davemarkle** [comment] 2024-11-01 19:49
[package.json](https://github.com/user-attachments/files/17603545/package.json)
[manifest.json](https://github.com/user-attachments/files/17603546/manifest.json)

and the js file is: 

import * as InboxSDK from '@inboxsdk/core';

InboxSDK.load(2, "sdk_sales_59248c4dae").then((sdk) => {
  // the SDK has been loaded, now do something with it!
  sdk.Compose.registerComposeViewHandler((composeView) => {
    // a compose view has come into existence, do something with it!
    composeView.addButton({
      title: "My Nifty Button!",
      iconUrl: chrome.runtime.getURL("logging.jpg"),
      onClick(event) {
        event.composeView.insertTextIntoBodyAtCursor("Hello World!");
      },
    });
  });
});

this is from a fresh installation of the hello world app. 

and is resulting in a CORS error which then produces many fails: 
![image](https://github.com/user-attachments/assets/ccc73991-7ea5-4932-8fe3-576e680dfa12)

Here's my directory structure... 
![image](https://github.com/user-attachments/assets/4badd332-f938-427d-8c64-7f2ec2988661)

I run npm install, npx webpack and it builds the dist folder fine. but when i load it in chrome and gmail, i get all the errors. 

Thank you so much for your help.

**Comment by Macil** [comment] 2024-11-01 20:50
The file https://www.inboxsdk.com/build/platform-implementation.js is back online, so the original issue here is fixed now. Note that we no longer regularly update this remote-loaded MV2 version of the InboxSDK and Chrome is gradually removing support for MV2 extensions, so it is still recommended to upgrade to the MV3-compatible version of the InboxSDK.

**Closed by Macil** 2024-11-01 20:50 UTC
Labels: invalid

**Comment by davemarkle** [comment] 2024-11-01 20:55
That's great. I can confirm that I am not receiving CORS errors or a 404 any longer. 

However, I am using the v3 manifest and it shouldn't have been necessary. 

Can you tell me what in the above code is incorrect? I loaded the hello world out of the box and got this error.

**Comment by Macil** [comment] 2024-11-01 20:55
@davemarkle The files you've shown look right but I did not expect that console output including failed requests for `https://www.inboxsdk.com/build/platform-implementation.js` and I'm not clear how that could be happening. Could you have multiple extensions enabled at once and some of them are using the MV2 version of the InboxSDK? If you click "inboxsdk.js" in the console there (okay, I assume you will no longer get these errors as the URL doesn't 404 any more, but you can filter the network page for requests to inboxsdk.com and see the file making the requests there too), then it will lead you to the file making the request, which I expect is an old mv2 version of inboxsdk.js, possibly in another extension.

**Comment by davemarkle** [comment] 2024-11-01 21:46
Omg. You're right. I hadn't disabled our old version. I removed it from chrome this morning but then didn't remove it from Arc. 

Thank you so much for your help with that.  That is A+ blind debugging.

**Comment by shashikiran-im** [comment] 2024-11-05 06:04
Hi Macil / Aleemstreak, 

Thanks for making the JS library (platform-implementation.js) available in the path. 

**Need Clarification:** 
May I know till how long you keep the JS library (platform-implementation.js) in the path for MV2 support?  
Though we are already in the process of migrating our extension from MV2 to MV3, but want to know your timeline until you keep the library in the path. 

Thanks in Advance,
Shashikiran
