### ISSUE TITLE
Bug: Toolbars.registerThreadButton not working

### ISSUE THREAD

**Issue by thebinod7** [InboxSDK/InboxSDK#1100] opened 2023-12-08 10:03 UTC
Hi,

I have a chrome extension built using InboxSDK. I have implemented a Toolbars.registerThreadButton method to inject the button inside Gmai Inbox Thread. It was working before but suddenly has stopped working. Any update on this?

Thanks!

**Comment by wegry** [comment] 2023-12-08 18:38
Closing as dupe of #1080 based on [this comment](https://github.com/InboxSDK/InboxSDK/issues/1080#issuecomment-1847148557).

**Closed by wegry** 2023-12-08 18:38 UTC
Labels: status: Unconfirmed
