### ISSUE TITLE
registerComposeViewHandler not binding on reply compose

### ISSUE THREAD

**Issue by oscardimanno** [InboxSDK/InboxSDK#915] opened 2023-06-05 14:34 UTC
**Describe the bug**
Binding on the Compose.registerComposeViewHandler event not working everytime.
Work on normal compose modal and on full screen conversation but enabling the right or below Reading pane the ComposeViewHandler will not call the callback function

**To Reproduce**

1. Bind a function on Compose.registerComposeViewHandler
2. Go into Gmail settings
3. Go into "Inbox" tab
4. Enable "Reading pane" using "Right of inbox"
5. Go to thread view
6. Click on conversation
7. In the right pane click to reply the conversation
8. Now callback function not firing!

**Expected behavior**
The firing of the callback function

**Screenshots**

**Add any other context about the problem here if anything**

**Comment by wegry** [comment] 2023-07-19 14:33
@oscardimanno, maybe there's something I'm missing here in the repro steps, but with [this comment](https://github.com/InboxSDK/InboxSDK/pull/951#issuecomment-1642172398) (reused from #801), I can't seem to reproduce the issue.

Has the issue been reliably reproducible?

**Comment by Hamdan85** [comment] 2024-02-06 17:30
It seems that it was marked as done in your sdk issues, but it is still happening. 

Im using inbox SDK core version 1.2.8.

**Comment by wegry** [comment] 2024-02-06 19:34
@Hamdan85 can you repro with `@inboxsdk/core@1.2.28`?

**Comment by Hamdan85** [comment] 2024-02-06 20:00
> @Hamdan85 can you repro with `@inboxsdk/core@1.2.28`?

is it published on npm?
![image](https://github.com/InboxSDK/InboxSDK/assets/1886026/051634ad-ba8f-4d2e-9f98-0c04275a988b)

> 50 verbose stack @inboxsdk/core: No matching version found for @inboxsdk/core@1.2.28.
> 50 verbose stack     at module.exports (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
> 50 verbose stack     at RegistryFetcher.manifest (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:125:22)
> 50 verbose stack     at async Arborist.[nodeFromEdge] (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:19)
> 50 verbose stack     at async Arborist.[buildDepStep] (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
> 50 verbose stack     at async Arborist.buildIdealTree (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
> 50 verbose stack     at async Promise.all (index 1)
> 50 verbose stack     at async Arborist.reify (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
> 50 verbose stack     at async Install.exec (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/lib/commands/install.js:145:5)
> 50 verbose stack     at async module.exports (/home/hamdan/.asdf/installs/nodejs/16.19.0/lib/node_modules/npm/lib/cli.js:78:5)

**Comment by Hamdan85** [comment] 2024-02-06 20:05
you meant 2.1.28.

The problem is fixed in the latest version. 

Im sorry, I don't know why my upgrade process wasn't updating it to the latest. ;)

thanks

**Closed** 2024-02-07 12:32 UTC
Labels: status: Unconfirmed
