### ISSUE TITLE
Bug: When logged in on Gmail, the placement of the added navigation item differs between email address ending with "@gmail.com" and business email address (ending with "@organization.com")

### ISSUE THREAD

**Issue by gencalda** [InboxSDK/InboxSDK#1010] opened 2023-08-30 13:44 UTC
**Describe the bug**
- When logged in on Gmail, the placement of the added navigation item differs between email address ending with "@gmail.com" and business email address (ending with "@organization.com")
- Also, the icon of the NavMenu is not being displayed when logged in with emails ending with "@gmail.com"

**To Reproduce**

1. Add a navigation item to the NavMenu using `NavMenu.addNavItem`
2. Log in to Gmail using a business email address  (ending with "@organization.com"). Check the placement of the added navigation item
3.  Log in to Gmail using a business email address  (ending with "@gmail.com"). Check the placement of the added navigation item. It's different from the placement of email address ending with "@organization.com". Aside from that, the icon is not being displayed.

**Expected behavior**
When logged in on Gmail for both email addresses ending with "@gmail.com" and business email addresses (ending with "@organization.com"): 
- The placement of the added navigation item using `NavMenu.addNavItem` should be consistent 
- The icon should be displayed for the added navigation item

**Screenshots**
| Logged in using an email address ending with "@organization.com" |
|------------------------------------------------------------------|
| ![Screenshot 2023-08-30 at 4 58 09 PM](https://github.com/InboxSDK/InboxSDK/assets/15812704/c4195029-664c-49f6-af17-c8076e63c87d) |

| Logged in using an email address ending with "@gmail.com"  |
|------------------------------------------------------------------|
|  ![Screenshot 2023-08-30 at 9 31 14 PM](https://github.com/InboxSDK/InboxSDK/assets/15812704/4000b848-c39f-4f78-b363-8fe83c8ef7b9) |

**Add any other context about the problem here if anything**

**Comment by gencalda** [comment] 2023-08-30 17:27
> @gencalda in the second screenshot, Google Chat and Meet are not enabled. Does the behavior differ between @gmail.com and business email addresses if chat and meet are enabled there?
> 
> > The placement of the added navigation item using NavMenu.addNavItem should be consistent
> 
> By placement, do you mean padding and/or alignment? Or do you mean above or below "Labels"?

@wegry  Thanks for the prompt response. After checking, I was able to confirm that @gmail.com and business email addresses are not relevant. Enabling/Disabling the chat and meet affects the placement of the added navigation items. 

By placement, I meant the location where the navigation item was injected. Before the “More” option, the one in the yellow rectangle in the screenshot below:
<img width="323" alt="Screenshot 2023-08-31 at 1 23 36 AM" src="https://github.com/InboxSDK/InboxSDK/assets/15812704/cc1c3642-44a9-4472-8e09-156128fe4b63">

Here's a video with chat and meet disabled. If the added navigation item is closed, it's located at the bottom of the screen:

https://github.com/InboxSDK/InboxSDK/assets/15812704/a09c7e5c-86f4-42c5-9207-a4340ff5fd67

**Comment by wegry** [comment] 2023-08-30 17:33
This seems to be a dupe of https://github.com/InboxSDK/InboxSDK/issues/893#issuecomment-1500384571.

**Closed** 2023-08-30 20:18 UTC
Labels: status: Unconfirmed
