### ISSUE TITLE
Bug: ThreadViewHandler not firing in Preview mode in gmail

### ISSUE THREAD

**Issue by teamstand-anup** [InboxSDK/InboxSDK#789] opened 2022-10-12 06:19 UTC
When the gmail is in preview mode (Select split vertically) and you click on any thread the threadViewHandler (function attached to registerThreadViewHandler) is not firing.
Happening in Chrome browser version Version 106.0.5249.119 (Official Build) (64-bit)
Though it doesnot seem to be browser version related.
The same thing worked last night so I am guessing that this is due to some changes in gmail dom maybe.

Thanks in advance

**Comment by kuhnster01** [comment] 2022-10-12 16:45
We are seeing this issue when an email is opened with the Gmail reading pane active. I think there may also be a related issue without the Gmail reading pane inactive.

**Comment by aleemstreak** [comment] 2022-10-12 17:06
Do you have repro steps for the related issue?

**Comment by aleemstreak** [comment] 2022-10-12 17:25
Also a minimal extension that reproduces the issue would be very helpful

**Comment by kuhnster01** [comment] 2022-10-12 18:22
It’s late on our side of the world and we will try help tomorrow if we have new information to share. We briefly tried to look in the GitHub repro but I don’t think we know our way around it yet.

As explained in the description on this issue, when a user opens an email while the reading pane active, we are no longer getting the call so that we can identify which thread the user has clicked on. 

We still see the Thread-F info in the DOM.

**Comment by wegry** [comment] 2022-10-12 19:28
Closed by #791.

**Comment by teamstand-anup** [comment] 2022-10-20 09:52
This issue is back. Maybe another build for Gmail UI.
Can we re-open this issue or should we create a new ticket?

**Comment by teamstand-shahrukh** [comment] 2022-10-21 06:20
The classname has been updated in some regions from `nH PeIF1d` to `nH a98 iY`.

**Closed** 2022-10-21 12:14 UTC
Labels: bug

**Comment by 1TheMuffinMan** [comment] 2023-03-16 18:17
This issue seems to be back again. Both `sdk.Conversations.registerMessageViewHandler` and `sdk.Conversations.registerThreadViewHandler` aren't being triggered for a conversation if the preview pane is activated via the split view (horizontal or vertical)
